[toolchain]
anchor_version = "0.29.0"

[features]
seeds = false
skip-lint = false

[programs.localnet]
anchor = "GohJtCgJB3nYQBtWrSyxHcS2VRnAL6cs3ifJYKVob4ZK"

[programs.devnet]
anchor = "GohJtCgJB3nYQBtWrSyxHcS2VRnAL6cs3ifJYKVob4ZK"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
